//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSIGNACIONE
    {
        public int ID_CONSIGNACION { get; set; }
        public int ID_PROPIEDAD { get; set; }
        public int ID_PROPIETARIO { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public decimal PORCENTAJE_COMISION { get; set; }
    
        public virtual PROPIEDADE PROPIEDADE { get; set; }
        public virtual PROPIETARIO PROPIETARIO { get; set; }
    }
}
