//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGENES_PROPIEDAD
    {
        public int ID_IMAGEN { get; set; }
        public int ID_PROPIEDAD { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual PROPIEDADE PROPIEDADE { get; set; }
    }
}
