//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borrador.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INMOBILIARIAEntities : DbContext
    {
        public INMOBILIARIAEntities()
            : base("name=INMOBILIARIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARRIENDO> ARRIENDOS { get; set; }
        public virtual DbSet<CIUDADE> CIUDADES { get; set; }
        public virtual DbSet<CLIENTE> CLIENTES { get; set; }
        public virtual DbSet<CONSIGNACIONE> CONSIGNACIONES { get; set; }
        public virtual DbSet<DETALLES_ORDEN> DETALLES_ORDEN { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOS { get; set; }
        public virtual DbSet<ESTADOS_PROPIEDAD> ESTADOS_PROPIEDAD { get; set; }
        public virtual DbSet<ORDENES_COMPRA> ORDENES_COMPRA { get; set; }
        public virtual DbSet<PROPIEDADE> PROPIEDADES { get; set; }
        public virtual DbSet<PROPIEDADES_MODELO> PROPIEDADES_MODELO { get; set; }
        public virtual DbSet<PROPIETARIO> PROPIETARIOS { get; set; }
        public virtual DbSet<PROVEEDORE> PROVEEDORES { get; set; }
        public virtual DbSet<PROYECTO> PROYECTOS { get; set; }
        public virtual DbSet<SEDE> SEDES { get; set; }
        public virtual DbSet<TIPOS_PROPIEDAD> TIPOS_PROPIEDAD { get; set; }
        public virtual DbSet<TIPOS_PROVEEDOR> TIPOS_PROVEEDOR { get; set; }
        public virtual DbSet<TIPOS_VISITA> TIPOS_VISITA { get; set; }
        public virtual DbSet<VENTA> VENTAS { get; set; }
        public virtual DbSet<VISITA> VISITAS { get; set; }
    }
}
