//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDENES_COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDENES_COMPRA()
        {
            this.DETALLES_ORDEN = new HashSet<DETALLES_ORDEN>();
        }
    
        public int ID_ORDEN { get; set; }
        public int ID_PROVEEDOR { get; set; }
        public int ID_EMPLEADO { get; set; }
        public System.DateTime FECHA_ORDEN { get; set; }
        public decimal TOTAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLES_ORDEN> DETALLES_ORDEN { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PROVEEDORE PROVEEDORE { get; set; }
    }
}
