//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPIEDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROPIEDADE()
        {
            this.ARRIENDOS = new HashSet<ARRIENDO>();
            this.CONSIGNACIONES = new HashSet<CONSIGNACIONE>();
            this.VENTAS = new HashSet<VENTA>();
            this.VISITAS = new HashSet<VISITA>();
        }
    
        public int ID_PROPIEDAD { get; set; }
        public string TITULO { get; set; }
        public string DESCRIPCION { get; set; }
        public int ID_TIPO_PROPIEDAD { get; set; }
        public Nullable<decimal> AREA_M2 { get; set; }
        public Nullable<int> HABITACIONES { get; set; }
        public Nullable<int> BANOS { get; set; }
        public Nullable<int> PARQUEADEROS { get; set; }
        public Nullable<short> ANIO_CONSTRUCCION { get; set; }
        public string DIRECCION { get; set; }
        public int ID_CIUDAD { get; set; }
        public Nullable<decimal> PRECIO_VENTA { get; set; }
        public Nullable<decimal> PRECIO_ARRIENDO { get; set; }
        public int ID_ESTADO_PROPIEDAD { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARRIENDO> ARRIENDOS { get; set; }
        public virtual CIUDADE CIUDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSIGNACIONE> CONSIGNACIONES { get; set; }
        public virtual ESTADOS_PROPIEDAD ESTADOS_PROPIEDAD { get; set; }
        public virtual PROPIEDADES_MODELO PROPIEDADES_MODELO { get; set; }
        public virtual TIPOS_PROPIEDAD TIPOS_PROPIEDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTA> VENTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VISITA> VISITAS { get; set; }
    }
}
