//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPIEDADES_MODELO
    {
        public int ID_PROPIEDAD { get; set; }
        public int ID_PROYECTO { get; set; }
        public Nullable<decimal> COSTO_DECORACION { get; set; }
        public Nullable<System.DateTime> FECHA_DECORACION { get; set; }
    
        public virtual PROPIEDADE PROPIEDADE { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
