//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDORE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVEEDORE()
        {
            this.ORDENES_COMPRA = new HashSet<ORDENES_COMPRA>();
        }
    
        public int ID_PROVEEDOR { get; set; }
        public string NOMBRE_COMERCIAL { get; set; }
        public string NIT { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public int ID_TIPO_PROVEEDOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDENES_COMPRA> ORDENES_COMPRA { get; set; }
        public virtual TIPOS_PROVEEDOR TIPOS_PROVEEDOR { get; set; }
    }
}
