//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROYECTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROYECTO()
        {
            this.PROPIEDADES_MODELO = new HashSet<PROPIEDADES_MODELO>();
        }
    
        public int ID_PROYECTO { get; set; }
        public string NOMBRE { get; set; }
        public int ID_CIUDAD { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<System.DateTime> FECHA_LANZAMIENTO { get; set; }
        public Nullable<System.DateTime> FECHA_ENTREGA_ESTIMADA { get; set; }
        public string DESARROLLADOR { get; set; }
    
        public virtual CIUDADE CIUDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPIEDADES_MODELO> PROPIEDADES_MODELO { get; set; }
    }
}
