//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public int ID_VENTA { get; set; }
        public int ID_PROPIEDAD { get; set; }
        public int ID_CLIENTE { get; set; }
        public int ID_EMPLEADO { get; set; }
        public System.DateTime FECHA_VENTA { get; set; }
        public decimal PRECIO_FINAL { get; set; }
        public decimal COMISION { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PROPIEDADE PROPIEDADE { get; set; }
    }
}
