//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITA
    {
        public int ID_VISITA { get; set; }
        public int ID_PROPIEDAD { get; set; }
        public int ID_CLIENTE { get; set; }
        public int ID_EMPLEADO { get; set; }
        public int ID_TIPO_VISITA { get; set; }
        public System.DateTime FECHA_HORA { get; set; }
        public string COMENTARIOS { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PROPIEDADE PROPIEDADE { get; set; }
        public virtual TIPOS_VISITA TIPOS_VISITA { get; set; }
    }
}
